default:
  project_name: "collabrators"
  dataset: "wangwenjie"
colors:
  tissue:
    Liver: "#5050FFFF"
    Heart: "#CE3D32FF"
    Hindlimb: "#749B58FF"
    Midbrain: "#F0E685FF"
    Branchial arch: "#466983FF"
    Brain mesenchyme: "#345698FF"
    Forebrain: "#BA6338FF"
    Gut: "#5DB1DDFF"
    Forelimb: "#802268FF"
    Hindbrain: "#6BD76BFF"
    AGM: "#D595A7FF"
    Spinal cord: "#924822FF"
    Epidermis: "#837B8DFF"
    Embryo membrane: "#C75127FF"
    Jaw and tooth: "#D58F5CFF"
    Cavity: "#7A65A5FF"
    Somite: "#E4AF69FF"
    Cartilage: "#CDDEB7FF"
    Lung: "#612A79FF"
    Kidney: "#AE1F63FF"
    Gonad: "#E7C76FFF"
    Blood vessel: "#5A655EFF"
    Diencephalon: "#CC9900FF"
    Muscle: "#99CC00FF"
    Ear: "#A9A9A9FF"
    Caudal neuropore: "#FF8800FF"
    Mesenchyme: "#FFCC00FF"
    Optic vesicle: "#CC22AAFF"
    Umbilical cord: "#22CCAAFF"
    others: "#222222"
    Others: "#222222"
    CNS: "#BA6338FF"
    G and K: "#D595A7FF"
  stage:
    CS12: "#FF0000B3"
    CS14: "#00FF00B3"
    CS18: "#0000FFB3"
    E9.5: "#FF0000B3"
    E11.5: "#00FF00B3"
    E13.5: "#0000FFB3"